### PR TITLE
(fix) hasOwnProperty is an Object instance method

### PR DESCRIPTION
**Pull request by philBrown**
Change incorrect references of

    Object.hasOwnProperty

to

    Object.prototype.hasOwnProperty

### CODE REVIEW

**Comment by douglascrockford** [comment]
What is the bug that this fixes?

**Comment by philBrown** [comment]
According to the specification (and the browser I was trying to use this with), `hasOwnProperty` is an `Object.prototype` method and `Object.hasOwnProperty` does not exist

**Comment by douglascrockford** [comment]
That does not answer my question. What bug does this repair?

**Comment by philBrown** [comment]
Running the current `parse_json` function (from either `parse_json.js` or `parse_json_state.js`) in a browser that implements only the specification (ie, does not implement `Object.hasOwnProperty` as a function) results in a runtime error to the tune of

> Cannot read property 'call' of undefined

This PR fixes that error by using `Object.prototype.hasOwnProperty` which **is** part of the specification and is implemented by a wider range of browsers.

Would you like me to raise an issue first?

**Comment by douglascrockford** [comment]
What browser does this?

**Comment by philBrown** [comment]
The one I was having trouble with was an embedded [ANT browser](https://en.wikipedia.org/wiki/Fresco_(web_browser)).

I know you probably don't aim to support something like this but making this change works correctly. As far as I can tell, there is no official documentation for `hasOwnProperty` as a static method of `Object` and apart from the two line changes in this pull request, all other calls to the method are made via `Object.prototype.hasOwnProperty` so if nothing else, this makes the code consistent.

**Comment by douglascrockford** [comment]
This code is stable and near end of life. I will not make changes unless they fix real problems.

Object inherits from Object.prototype, so correct implementations will find hasOwnProperty.

**Comment by philBrown** [comment]
If that's the case, why do you not use `Object.hasOwnProperty` everywhere instead of `Object.prototype.hasOwnProperty`?

Examples [here](https://github.com/douglascrockford/JSON-js/blob/master/json_parse.js#L342) and [here](https://github.com/douglascrockford/JSON-js/blob/master/json_parse_state.js#L391).

**Comment by patrikvarga** [comment]
> I will not make changes unless they fix real problems.

@douglascrockford would you mind clarifying how the above is not a real problem?

**Comment by disruptek** [comment]
This is ridiculous.

You said yourself that correct implementations will not be affected by the change, but clearly, "incorrect" implementations will be helped.  That is the real problem that this change solves, and with minimal collateral impact.

**Comment by patrikvarga** [comment]
@douglascrockford Any idea why my previous comment and Andy Davidoff's (@disruptek ?) previous comment are not visible anymore?

I can't remember my comment exactly, but the point was that calling other people's real problem "not a real problem" is not very helpful.

Andy's previous comment was:

> This is ridiculous.
> 
> You said yourself that correct implementations will not be affected by the change, but clearly, "incorrect" implementations will be helped. That is the real problem that this change solves, and with minimal collateral impact.

**Pull request closed without merging**
